### ISSUE TITLE
Feature Request: Toggle Overlay

### ISSUE THREAD

**Issue by Boobies** [Schauweg/TimeToLive#2]
Hi,

I mostly use this whenever I'm debugging redstone contraptions having to do with TNT. However, I don't need it when I'm actually running them so it would be nice if there were some setting to turn the information off when it is not required. Perhaps through a menu available via Mod Menu or through a command, whichever works for you.

Cheers,
Bogdan

**Comment by Schauweg** [comment]
Thanks for the suggestion! I'll see what I can do once I have time to do it.

**Comment by Schauweg** [comment]
Added the feature with the new version. Thanks again for the great suggestion!
